package com.example.assistente.rules

import java.time.LocalDate
import java.time.Period

import com.example.assistente.model.dto.ExamePacienteDTO
import com.example.assistente.model.dto.PacienteDTO
import com.example.assistente.model.dto.ResultadoDTO
import com.example.assistente.drools.model.ExamesDTO
import com.example.assistente.drools.Indexadores
import com.example.assistente.drools.model.ResultadosDTO
import com.example.assistente.model.type.TiposExames
import com.example.assistente.model.type.Status
import com.example.assistente.model.type.SexoPaciente
import java.util.Arrays

    
//regras para hemacias
rule "hemacia"
	when
	    ResultadosDTO($resultados: resultados)
	    ExamesDTO($exames: exames)
		$exame: ExamePacienteDTO(tipoExame == TiposExames.hemacias) from $exames
	then
		System.out.println("hemacia");
        $resultados.add(ResultadoDTO.builder()
            .value($exame.getValue())
            .tipoExame($exame.getTipoExame())
            .build());
	end
	
rule "valor hemacia crianca"
	when
		PacienteDTO(idade >= 2, idade < 18)
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias) from $resultados
	then
		System.out.println("hemacia crianca");
		$resultado.setValues(Indexadores.Hemacias.criancas);
	end
	
rule "valor hemacia homem"
	when
		PacienteDTO(idade >= 18, sexo == SexoPaciente.masculino)
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias) from $resultados
	then
		System.out.println("hemacia homem");
		$resultado.setValues(Indexadores.Hemacias.homens);
	end
	
rule "valor hemacia mulher"
	when
		PacienteDTO(idade < 18, sexo == SexoPaciente.feminino)
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias) from $resultados
	then
		System.out.println("hemacia mulher");
		$resultado.setValues(Indexadores.Hemacias.mulheres);
	end

rule "hemacia low"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias, values != null, value < values[0]) from $resultados
	then
		System.out.println("hemacia low");
		$resultado.setStatus(Status.abaixo);
	end

rule "hemacia high"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias, values != null, value > values[1]) from $resultados
	then
		System.out.println("hemacia high");
		$resultado.setStatus(Status.acima);
	end

rule "hemacia ideal"
	when
		ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias, values != null, value < values[1], value > values[0]) from $resultados
	then
		System.out.println("hemacia ideal");
		$resultado.setStatus(Status.ideal);
	end

rule "hemacia low status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias, values != null, status == Status.abaixo) from $resultados
	then
		$resultado.setMensagem("Consulte um medico, suas hemacias estao baixas");
	end

rule "hemacia high status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias, status == Status.acima) from $resultados
	then
		$resultado.setMensagem("Consulte um medico, suas hemacias estao altas");
	end

rule "hemacia ideal status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias, status == Status.ideal) from $resultados
	then
		$resultado.setMensagem("Parabens, suas hemacias estao em ordem!");
	end
	
	
	//regras para hemoglobina
rule "hemoglobina"
	when
	    ResultadosDTO($resultados: resultados)
	    ExamesDTO($exames: exames)
		$exame: ExamePacienteDTO(tipoExame == TiposExames.hemoglobina) from $exames
	then
        $resultados.add(ResultadoDTO.builder()
            .value($exame.getValue())
            .tipoExame($exame.getTipoExame())
            .build());
	end
	
rule "valor hemoglobina recem nascido"
	when
		PacienteDTO(idade < 2)
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemoglobina) from $resultados
	then
		$resultado.setValues(Indexadores.Hemoglobina.recemNascidos);
	end
	
rule "valor hemoglobina crianca"
	when
		PacienteDTO(idade >= 2, idade < 18)
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemoglobina) from $resultados
	then
		$resultado.setValues(Indexadores.Hemoglobina.criancas);
	end
	
rule "valor hemoglobina homem"
	when
		PacienteDTO(idade >= 18, sexo == SexoPaciente.masculino)
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemoglobina) from $resultados
	then
		$resultado.setValues(Indexadores.Hemoglobina.homens);
	end
	
rule "valor hemoglobina mulher"
	when
		PacienteDTO(idade < 18, sexo == SexoPaciente.feminino)
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemoglobina) from $resultados
	then
		$resultado.setValues(Indexadores.Hemoglobina.mulheres);
	end

rule "hemoglobina low"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemoglobina, values != null, value < values[0]) from $resultados
	then
		$resultado.setStatus(Status.abaixo);
	end

rule "hemoglobina high"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemoglobina, values != null, value > values[1]) from $resultados
	then
		$resultado.setStatus(Status.acima);
	end

rule "hemoglobina ideal"
	when
		ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemoglobina, values != null, value < values[1], value > values[0]) from $resultados
	then
		$resultado.setStatus(Status.ideal);
	end

rule "hemoglobina low status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemoglobina, status == Status.abaixo) from $resultados
	then
		$resultado.setMensagem("Consulte um medico, suas hemoglobina está baixas");
	end

rule "hemoglobina high status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemoglobina, status == Status.acima) from $resultados
	then
		$resultado.setMensagem("Consulte um medico, sua hemoglobina está altas");
	end

rule "hemoglobina ideal status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemoglobina, status == Status.ideal) from $resultados
	then
		$resultado.setMensagem("Parabens, sua hemoglobina está em ordem!");
	end