package com.example.assistente.rules
dialect "mvel"

import java.time.LocalDate
import java.time.Period

import com.example.assistente.model.dto.ExamePacienteDTO
import com.example.assistente.model.dto.PacienteDTO
import com.example.assistente.model.dto.ResultadoDTO
import com.example.assistente.drools.model.ExamesDTO
import com.example.assistente.drools.Indexadores
import com.example.assistente.drools.Idade
import com.example.assistente.drools.model.ResultadosDTO
import com.example.assistente.model.type.TiposExames
import com.example.assistente.model.type.Status
import com.example.assistente.model.type.SexoPaciente
import java.util.Arrays

    
//regras para hemacias
rule "hemacia"
salience 3
	when
	    ResultadosDTO($resultados: resultados)
	    ExamesDTO($exames: exames)
		$exame: ExamePacienteDTO(tipoExame == TiposExames.hemacias) from $exames
	then
		System.out.println("hemacia");
        $resultados.add(ResultadoDTO.builder()
            .value($exame.value)
            .tipoExame($exame.tipoExame)
            .build());
	end
	
rule "valor hemacia crianca"
salience 2
	when
		PacienteDTO(idade >= Idade.crianca, idade < Idade.adulto)
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias) from $resultados
	then
		System.out.println("hemacia crianca");
		$resultado.values = Indexadores.Hemacias.criancas;
	end
	
rule "valor hemacia homem"
salience 2
	when
		PacienteDTO(idade >= Idade.adulto, sexo == SexoPaciente.masculino)
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias) from $resultados
	then
		System.out.println("hemacia homem");
		$resultado.values = Indexadores.Hemacias.homens;
	end
	
rule "valor hemacia mulher"
salience 2
	when
		PacienteDTO(idade >= Idade.adulto, sexo == SexoPaciente.feminino)
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias) from $resultados
	then
		System.out.println("hemacia mulher");
		$resultado.values = Indexadores.Hemacias.mulheres;
	end
	

//regras para hemoglobina
rule "hemoglobina"
salience 3
	when
	    ResultadosDTO($resultados: resultados)
	    ExamesDTO($exames: exames)
		$exame: ExamePacienteDTO(tipoExame == TiposExames.hemoglobina) from $exames
	then
        $resultados.add(ResultadoDTO.builder()
            .value($exame.getValue())
            .tipoExame($exame.getTipoExame())
            .build());
	end
	
rule "valor hemoglobina recem nascido"
salience 2
	when
		PacienteDTO(idade < Idade.crianca)
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemoglobina) from $resultados
	then
		$resultado.setValues(Indexadores.Hemoglobina.recemNascidos);
	end
	
rule "valor hemoglobina crianca"
salience 2
	when
		PacienteDTO(idade >= Idade.crianca, idade < Idade.adulto)
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemoglobina) from $resultados
	then
		$resultado.setValues(Indexadores.Hemoglobina.criancas);
	end
	
rule "valor hemoglobina homem"
salience 2
	when
		PacienteDTO(idade >= Idade.adulto, sexo == SexoPaciente.masculino)
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemoglobina) from $resultados
	then
		$resultado.setValues(Indexadores.Hemoglobina.homens);
	end
	
rule "valor hemoglobina mulher"
salience 2
	when
		PacienteDTO(idade < Idade.adulto, sexo == SexoPaciente.feminino)
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemoglobina) from $resultados
	then
		$resultado.setValues(Indexadores.Hemoglobina.mulheres);
	end
	
	