package com.example.assistente.rules
dialect "mvel"

import java.time.LocalDate
import java.time.Period

import com.example.assistente.model.dto.ExamePacienteDTO
import com.example.assistente.model.dto.PacienteDTO
import com.example.assistente.model.dto.ResultadoDTO
import com.example.assistente.drools.model.ExamesDTO
import com.example.assistente.drools.Indexadores
import com.example.assistente.drools.model.ResultadosDTO
import com.example.assistente.model.type.TiposExames
import com.example.assistente.model.type.Status
import com.example.assistente.model.type.SexoPaciente
import java.util.Arrays

// intervalos
rule "low"
salience 1
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame.intervalo == true, tipoExame.custom == false, values != null, value < values[0]) from $resultados
	then
		System.out.println("low");
		$resultado.status = Status.abaixo;
	end

rule "high"
salience 1
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame.intervalo == true, tipoExame.custom == false, values != null, value > values[1]) from $resultados
	then
		System.out.println("high");
		$resultado.status = Status.acima;
	end

rule "hemacia ideal"
salience 1
	when
		ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame.intervalo == true, tipoExame.custom == false, values != null, value < values[1], value > values[0]) from $resultados
	then
		System.out.println("ideal");
		$resultado.status = Status.ideal;
	end