package com.example.assistente.rules
dialect "mvel"

import java.time.LocalDate
import java.time.Period

import com.example.assistente.model.dto.ExamePacienteDTO
import com.example.assistente.model.dto.PacienteDTO
import com.example.assistente.model.dto.ResultadoDTO
import com.example.assistente.drools.model.ExamesDTO
import com.example.assistente.drools.Indexadores
import com.example.assistente.drools.model.ResultadosDTO
import com.example.assistente.model.type.TiposExames
import com.example.assistente.model.type.Status
import com.example.assistente.model.type.SexoPaciente
import java.util.Arrays

// intervalos
rule "low status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(status == Status.abaixo, tipoExame.intervalo == true) from $resultados
	then
		$resultado.mensagem = $resultado.tipoExame.mensagens[0];
	end

rule "ideal status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(status == Status.ideal, tipoExame.intervalo == true) from $resultados
	then
		$resultado.mensagem = $resultado.tipoExame.mensagens[1];
	end
	
rule "high status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(status == Status.acima, tipoExame.intervalo == true) from $resultados
	then
		$resultado.mensagem = $resultado.tipoExame.mensagens[2];
	end
	
// menor que
rule "tipo exame false ideal status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(status == Status.ideal, tipoExame.intervalo == false) from $resultados
	then
		$resultado.mensagem = $resultado.tipoExame.mensagens[0];
	end

rule "tipo exame false alto status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(status == Status.acima, tipoExame.intervalo == false) from $resultados
	then
		$resultado.mensagem = $resultado.tipoExame.mensagens[1];
	end