package com.example.assistente.rules

import com.example.assistente.model.dto.ExamePacienteDTO
import com.example.assistente.model.dto.PacienteDTO
import com.example.assistente.model.dto.ResultadoDTO
import com.example.assistente.drools.model.ExamesDTO
import com.example.assistente.drools.model.ResultadosDTO
import com.example.assistente.model.type.TiposExames
import com.example.assistente.model.type.Status
import com.example.assistente.model.type.SexoPaciente
import java.util.Arrays

//regras para celulas vermelhas
rule "celula vermelha values"
	when
	    ResultadosDTO($resultados: resultados)
	    ExamesDTO($exames: exames)
		$exame: ExamePacienteDTO(tipoExame == TiposExames.globulos_vermelhos) from $exames
	then
        $resultados.add(ResultadoDTO.builder()
            .values(Arrays.asList(100.0, 150.0))
            .value($exame.getValue())
            .tipoExame($exame.getTipoExame())
            .build());
	end

rule "celula vermelha low"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.globulos_vermelhos, value < 100) from $resultados
	then
		$resultado.setStatus(Status.abaixo);
	end

rule "celula vermelha high"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.globulos_vermelhos, value > 150) from $resultados
	then
		$resultado.setStatus(Status.acima);
	end

rule "celula vermelha ideal"
	when
		ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.globulos_vermelhos, value < 150, value > 100) from $resultados
	then
		$resultado.setStatus(Status.ideal);
	end

rule "celula vermelha high status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.globulos_vermelhos, status == Status.abaixo) from $resultados
	then
		$resultado.setMensagem("Consulte um medico, suas celulas vermelhas estao baixas");
	end

rule "celula vermelha high status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.globulos_vermelhos, status == Status.acima) from $resultados
	then
		$resultado.setMensagem("Consulte um medico, suas celulas vermelhas estao altas");
	end

rule "celula vermelha ideal status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.globulos_vermelhos, status == Status.ideal) from $resultados
	then
		$resultado.setMensagem("Parabens, suas celulas vermelhas estao em ordem!");
	end
//regras para acido urico
rule "acido urico values masculino"
	when
	    ResultadosDTO($resultados: resultados)
	    ExamesDTO($exames: exames)
	    PacienteDTO( sexo == SexoPaciente.masculino)
		$exame: ExamePacienteDTO(tipoExame == TiposExames.acido_urico) from $exames
	then
        $resultados.add(ResultadoDTO.builder()
            .values(Arrays.asList(3.4, 7.0))
            .value($exame.getValue())
            .tipoExame($exame.getTipoExame())
            .build());
	end

//acido urico feminino
	rule "acido urico values feminino"
	when
	    ResultadosDTO($resultados: resultados)
	    ExamesDTO($exames: exames)
	    PacienteDTO(sexo == SexoPaciente.feminino)
		$exame: ExamePacienteDTO(tipoExame == TiposExames.acido_urico) from $exames
	then
        $resultados.add(ResultadoDTO.builder()
            .values(Arrays.asList(2.4, 6.0))
            .value($exame.getValue())
            .tipoExame($exame.getTipoExame())
            .build());
	end

rule "acido urico low status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.acido_urico, value < values[0]) from $resultados
	then
		$resultado.setStatus(Status.abaixo);
	end

rule "acido urico ideal status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.acido_urico, value < values[1] , value > values[0]) from $resultados
	then
		$resultado.setStatus(Status.ideal);
	end

rule "acido urico high status"
	when
		ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.acido_urico, value > values[1]) from $resultados
	then
		$resultado.setStatus(Status.acima);
	end

rule "acido urico high"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.acido_urico, status == Status.abaixo) from $resultados
	then
		$resultado.setMensagem("Consulte um medico, niveis de acido urico estao baixos");
	end

rule "acido urico low"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.acido_urico, status == Status.acima) from $resultados
	then
		$resultado.setMensagem("Consulte um medico, niveis de acido urico estao altas");
	end

rule "acido urico ideal"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.acido_urico, status == Status.ideal) from $resultados
	then
		$resultado.setMensagem("Parabens, niveis de acido urico estao em ordem!");
	end

//trigliceridios 
rule "trigliceridios jejum values"
	when
	    ResultadosDTO($resultados: resultados)
	    ExamesDTO($exames: exames)
		$exame: ExamePacienteDTO(tipoExame == TiposExames.triglicerideos, jejum == true) from $exames
	then
        $resultados.add(ResultadoDTO.builder()
            .values(Arrays.asList(150.0))
            .value($exame.getValue())
            .tipoExame($exame.getTipoExame())
            .build());
	end
	
	rule "trigliceridios nao jejum values"
	when
	    ResultadosDTO($resultados: resultados)
	    ExamesDTO($exames: exames)
		$exame: ExamePacienteDTO(tipoExame == TiposExames.triglicerideos, jejum == false) from $exames
	then
        $resultados.add(ResultadoDTO.builder()
            .values(Arrays.asList(175.0))
            .value($exame.getValue())
            .tipoExame($exame.getTipoExame())
            .build());
	end
rule "trigliceridios low"
	when
		ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.triglicerideos, value < values[0]) from $resultados
	then
		$resultado.setStatus(Status.abaixo);
	end

rule "trigliceridios high"
	when
		ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.triglicerideos, value > values[0]) from $resultados
	then
		$resultado.setStatus(Status.acima);
	end
	
rule "trigliceridios high status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.triglicerideos, status == Status.abaixo) from $resultados
	then
		$resultado.setMensagem("Consulte um medico, niveis de trigliceridios estao baixos");
	end

rule "trigliceridios low status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.triglicerideos, status == Status.acima) from $resultados
	then
		$resultado.setMensagem("Consulte um medico, niveis de trigliceridios estao altas");
	end
//Colesterol HDL
rule "colesterol hdl values"
	when
	    ResultadosDTO($resultados: resultados)
	    ExamesDTO($exames: exames)
		$exame: ExamePacienteDTO(tipoExame == TiposExames.hdl) from $exames
	then
        $resultados.add(ResultadoDTO.builder()
            .values(Arrays.asList(40.0, 60.0))
            .value($exame.getValue())
            .tipoExame($exame.getTipoExame())
            .build());
	end

rule "colesterol hdl low"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hdl, value < values[0]) from $resultados
	then
		$resultado.setStatus(Status.abaixo);
	end

rule "colesterol hdl high"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hdl, value > values[1]) from $resultados
	then
		$resultado.setStatus(Status.acima);
	end

rule "colesterol hdl ideal"
	when
		ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hdl, value < values[1], value > values[0]) from $resultados
	then
		$resultado.setStatus(Status.ideal);
	end

rule "colesterol hdl low status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hdl, status == Status.abaixo) from $resultados
	then
		$resultado.setMensagem("Consulte um medico, seus niveis de colesterol hdl estao baixos");
	end

rule "colesterol hdl high status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hdl, status == Status.acima) from $resultados
	then
		$resultado.setMensagem("Consulte um medico, seus niveis de colesterol hdl estao altos");
	end

rule "colesterol hdl ideal status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hdl, status == Status.ideal) from $resultados
	then
		$resultado.setMensagem("Parabens, seus niveis de colesterol hdl estao ordem!");
	end
