package com.example.assistente.rules
dialect "mvel"

import java.time.LocalDate
import java.time.Period

import com.example.assistente.model.dto.ExamePacienteDTO
import com.example.assistente.model.dto.PacienteDTO
import com.example.assistente.model.dto.ResultadoDTO
import com.example.assistente.drools.model.ExamesDTO
import com.example.assistente.drools.Indexadores
import com.example.assistente.drools.model.ResultadosDTO
import com.example.assistente.model.type.TiposExames
import com.example.assistente.model.type.Status
import com.example.assistente.model.type.SexoPaciente
import java.util.Arrays

rule "idade"
    when
        $paciente: PacienteDTO()
    then
    	System.out.println("idade");
        $paciente.setIdade(Period.between($paciente.getDataNasc(), LocalDate.now()).getYears());
        System.out.println($paciente.getIdade());
    end

//regras para hemacias
rule "hemacia"
	when
	    ResultadosDTO($resultados: resultados)
	    ExamesDTO($exames: exames)
		$exame: ExamePacienteDTO(tipoExame == TiposExames.hemacias) from $exames
	then
		System.out.println("hemacia");
        $resultados.add(ResultadoDTO.builder()
            .value($exame.value)
            .tipoExame($exame.tipoExame)
            .build());
	end
	
rule "valor hemacia crianca"
	when
		PacienteDTO(idade >= 2, idade < 18)
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias) from $resultados
	then
		System.out.println("hemacia crianca");
		$resultado.values = Indexadores.Hemacias.criancas;
	end
	
rule "valor hemacia homem"
	when
		PacienteDTO(idade >= 18, sexo == SexoPaciente.masculino)
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias) from $resultados
	then
		System.out.println("hemacia homem");
		$resultado.values = Indexadores.Hemacias.homens;
	end
	
rule "valor hemacia mulher"
	when
		PacienteDTO(idade < 18, sexo == SexoPaciente.feminino)
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias) from $resultados
	then
		System.out.println("hemacia mulher");
		$resultado.values = Indexadores.Hemacias.mulheres;
	end

rule "hemacia low"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias, values != null, value < values[0]) from $resultados
	then
		System.out.println("hemacia low");
		$resultado.status = Status.abaixo;
	end

rule "hemacia high"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias, values != null, value > values[1]) from $resultados
	then
		System.out.println("hemacia high");
		$resultado.status = Status.acima;
	end

rule "hemacia ideal"
	when
		ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias, values != null, value < values[1], value > values[0]) from $resultados
	then
		System.out.println("hemacia ideal");
		$resultado.status = Status.ideal;
	end

rule "hemacia low status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias, values != null, status == Status.abaixo) from $resultados
	then
		$resultado.mensagem = "Consulte um medico, suas hemacias estao baixas";
	end

rule "hemacia high status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias, status == Status.acima) from $resultados
	then
		$resultado.mensagem = "Consulte um medico, suas hemacias estao altas";
	end

rule "hemacia ideal status"
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hemacias, status == Status.ideal) from $resultados
	then
		$resultado.mensagem = "Parabens, suas hemacias estao em ordem!";
	end
	
	
//regras para acido urico
rule "acido urico values masculino"
	when
	    ResultadosDTO($resultados: resultados)
	    ExamesDTO($exames: exames)
	    PacienteDTO(sexo == SexoPaciente.masculino)
		$exame: ExamePacienteDTO(tipoExame == TiposExames.acido_urico) from $exames
	then
        $resultados.add(ResultadoDTO.builder()
            .values(Arrays.asList(3.4, 7.0))
            .value($exame.getValue())
            .tipoExame($exame.getTipoExame())
            .build());
	end

//acido urico feminino
	rule "acido urico values feminino"
	when
	    ResultadosDTO($resultados: resultados)
	    ExamesDTO($exames: exames)
	    PacienteDTO(sexo == SexoPaciente.feminino)
		$exame: ExamePacienteDTO(tipoExame == TiposExames.acido_urico) from $exames
	then
        $resultados.add(ResultadoDTO.builder()
            .values(Arrays.asList(2.4, 6.0))
            .value($exame.getValue())
            .tipoExame($exame.getTipoExame())
            .build());
	end

rule "acido urico low status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.acido_urico, value < values[0]) from $resultados
	then
		$resultado.setStatus(Status.abaixo);
	end

rule "acido urico ideal status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.acido_urico, value < values[1] , value > values[0]) from $resultados
	then
		$resultado.setStatus(Status.ideal);
	end

rule "acido urico high status"
	when
		ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.acido_urico, value > values[1]) from $resultados
	then
		$resultado.setStatus(Status.acima);
	end

rule "acido urico high"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.acido_urico, status == Status.abaixo) from $resultados
	then
		$resultado.setMensagem("Consulte um medico, niveis de acido urico estao baixos");
	end

rule "acido urico low"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.acido_urico, status == Status.acima) from $resultados
	then
		$resultado.setMensagem("Consulte um medico, niveis de acido urico estao altas");
	end

rule "acido urico ideal"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.acido_urico, status == Status.ideal) from $resultados
	then
		$resultado.setMensagem("Parabens, niveis de acido urico estao em ordem!");
	end

//trigliceridios 
rule "trigliceridios jejum values"
	when
	    ResultadosDTO($resultados: resultados)
	    ExamesDTO($exames: exames)
		$exame: ExamePacienteDTO(tipoExame == TiposExames.triglicerideos, jejum == true) from $exames
	then
	    System.out.println("trigliceridios jejum values");
        $resultados.add(ResultadoDTO.builder()
            .values(Arrays.asList(150.0))
            .maiorMelhor(false)
            .value($exame.getValue())
            .tipoExame($exame.getTipoExame())
            .build());
	end

	rule "trigliceridios nao jejum values"
    	when
    	    ResultadosDTO($resultados: resultados)
    	    ExamesDTO($exames: exames)
    		$exame: ExamePacienteDTO(tipoExame == TiposExames.triglicerideos, jejum == false) from $exames
    	then
    	    System.out.println("trigliceridios nao jejum values");
            $resultados.add(ResultadoDTO.builder()
                .values(Arrays.asList(175.0))
                .maiorMelhor(false)
                .value($exame.getValue())
                .tipoExame($exame.getTipoExame())
                .build());
    	end
	
	rule "trigliceridios nao jejum values 10 years"
	when
	    ResultadosDTO($resultados: resultados)
	    ExamesDTO($exames: exames)
	    $paciente: PacienteDTO(idade < 10)
	    eval($paciente.getIdade() < 10)
		$exame: ExamePacienteDTO(tipoExame == TiposExames.triglicerideos, jejum == false) from $exames
	then
	    System.out.println("trigliceridios nao jejum values 10 years");
        $resultados.add(ResultadoDTO.builder()
            .values(Arrays.asList(75.0))
            .value($exame.getValue())
            .tipoExame($exame.getTipoExame())
            .build());
	end

	rule "trigliceridios jejum values 10 years"
	when
	    ResultadosDTO($resultados: resultados)
	    ExamesDTO($exames: exames)
	    $paciente: PacienteDTO(idade < 10)
        eval($paciente.getIdade() < 10)
		$exame: ExamePacienteDTO(tipoExame == TiposExames.triglicerideos, jejum == true) from $exames
	then
	    System.out.println("trigliceridios jejum values 10 years");
	    System.out.println($paciente.getIdade());
        $resultados.add(ResultadoDTO.builder()
            .values(Arrays.asList(85.0))
            .value($exame.getValue())
            .tipoExame($exame.getTipoExame())
            .build());
	end

rule "trigliceridios ideal"
	when
		ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.triglicerideos, value <= values[0]) from $resultados
	then
		$resultado.setStatus(Status.ideal);
	end

rule "trigliceridios high"
	when
		ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.triglicerideos, value > values[0]) from $resultados
	then
		$resultado.setStatus(Status.acima);
	end
	
rule "trigliceridios high status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.triglicerideos, status == Status.ideal) from $resultados
	then
		$resultado.setMensagem("Parabens, niveis de trigliceridios estao em ordem!");
	end

rule "trigliceridios ideal status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.triglicerideos, status == Status.acima) from $resultados
	then
		$resultado.setMensagem("Consulte um medico, niveis de trigliceridios estão altos");
	end

//Colesterol HDL
rule "colesterol hdl values"
	when
	    ResultadosDTO($resultados: resultados)
	    ExamesDTO($exames: exames)
		$exame: ExamePacienteDTO(tipoExame == TiposExames.hdl) from $exames
	then
        $resultados.add(ResultadoDTO.builder()
            .values(Arrays.asList(40.0, 60.0))
            .value($exame.getValue())
            .tipoExame($exame.getTipoExame())
            .build());
	end

rule "colesterol hdl low"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hdl, value < values[0]) from $resultados
	then
		$resultado.setStatus(Status.abaixo);
	end

rule "colesterol hdl high"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hdl, value > values[1]) from $resultados
	then
		$resultado.setStatus(Status.acima);
	end

rule "colesterol hdl ideal"
	when
		ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hdl, value < values[1], value > values[0]) from $resultados
	then
		$resultado.setStatus(Status.ideal);
	end

rule "colesterol hdl low status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hdl, status == Status.abaixo) from $resultados
	then
		$resultado.setMensagem("Consulte um medico, seus niveis de colesterol hdl estao baixos");
	end

rule "colesterol hdl high status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hdl, status == Status.acima) from $resultados
	then
		$resultado.setMensagem("Consulte um medico, seus niveis de colesterol hdl estao altos");
	end

rule "colesterol hdl ideal status"
	when
	    ResultadosDTO($resultados: resultados)
		$resultado: ResultadoDTO(tipoExame == TiposExames.hdl, status == Status.ideal) from $resultados
	then
		$resultado.setMensagem("Parabens, seus niveis de colesterol hdl estao ordem!");
	end
