package com.example.assistente.rules
dialect "mvel"

import java.time.LocalDate
import java.time.Period

import com.example.assistente.model.dto.ExamePacienteDTO
import com.example.assistente.model.dto.PacienteDTO
import com.example.assistente.model.dto.ResultadoDTO
import com.example.assistente.drools.model.ExamesDTO
import com.example.assistente.drools.Indexadores
import com.example.assistente.drools.model.ResultadosDTO
import com.example.assistente.model.type.TiposExames
import com.example.assistente.model.type.Status
import com.example.assistente.model.type.SexoPaciente
import java.util.Arrays

// tp
rule "tp"
salience 3
	when
	    ResultadosDTO($resultados: resultados)
	    ExamesDTO($exames: exames)
		$exame: ExamePacienteDTO(tipoExame == TiposExames.tp) from $exames
	then
		System.out.println("tp");
        $resultados.add(ResultadoDTO.builder()
            .value($exame.value)
            .values(Indexadores.TTPATP.tp)
            .tipoExame($exame.tipoExame)
            .build());
	end
	
// ttpa
rule "ttpa"
salience 3
	when
	    ResultadosDTO($resultados: resultados)
	    ExamesDTO($exames: exames)
		$exame: ExamePacienteDTO(tipoExame == TiposExames.ttpa) from $exames
	then
		System.out.println("ttpa");
        $resultados.add(ResultadoDTO.builder()
            .value($exame.value)
            .values(Indexadores.TTPATP.ttpa)
            .tipoExame($exame.tipoExame)
            .build());
	end
